config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :posts do
    resources :comments
  end
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:description))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/views/comments/_comment.html.erb
		<h4> <%=comment.description%></h4>
		<h5><%=comment.user.email%><h5>
	
	
		<%= link_to "Edit", edit_post_comment_path(comment.post, comment)%>
		<%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }%>
		<hr/>
		

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>
	<div class="form-group">

	<p class="des"><%= f.text_area :description, :class => "form_control"%></p>
	<%= button_tag(type: 'submit', class: "btn btn-warning") do %>
    <i class="icon-ok icon-white"></i> Save
  <% end %>
  </div>
	<%end%>

app/views/comments/edit.html.erb
<h3 style="color:#FE6F5E">Edit Information</h3><br/>
<%= form_for([@post, @post.comments.build]) do |f|%>
	<div class="form-group">
	<%= f.text_area :description, :class => "form_control"%></br>
	<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    <i class="icon-ok icon-white"></i> Save
  	<%end%>
	</div>
	<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prtl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	<h1 style="background-color:lightgrey"><%= link_to "Abhilash's Forum For The Real Enthusiasts ", root_path%></h1>

	<% if user_signed_in?%>
				<%= link_to "New Post", new_post_path%>
				<%= link_to "sign_out", destroy_user_session_path, method: :delete%>
				<% else%>
				
					<%= link_to "Sign Up", new_user_registration_path%>			
					<%=link_to "Sign In", new_user_session_path%>
					
	<%end%>


 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 
<%= yield %>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<h3> create posts</h3>

<%= form_for @post do |p|%>

<label> Title </label><br/>
<%= p.text_field :title%><br/>

<label> Description</label><br/>
<%= p.text_area :description%><br/>

<%= p.submit %>
<%end%>  

app/views/posts/index.html.erb
<% @posts.each do |post|%>

<h4 style="color:red"><%= link_to post.title.upcase, post%></h4>



<h5 style="color:#CD5B45">by <%= post.user.email%> created at <%= time_ago_in_words(post.created_at)%> ago </h5>  </br> </br>

<%end%>

app/views/posts/new.html.erb
<h3> create posts</h3>

<%= form_for @post do |p|%>

<div class="form-group">
<label> Title </label><br/>
<%= p.text_field :title, :class => "form_control"%><br/>
</div>

<div class="form-group">
<label> Description</label><br/>
<%= p.text_area :description, :class => "form_control"%><br/>
</div>


<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    <i class="icon-ok icon-white"></i> Save
  <% end %>


<%#= p.submit, :class => "btn btn-default" %>
<%end%>  

app/views/posts/show.html.erb
	<h3 style="color:#D70A53"><%= @post.title%></h3>
	<p><%= @post.description%></p>

		<h3 style="color:#7F1734">
			<%= @post.comments.count%>
			Comments
		</h3>
		<%= render @post.comments%> 	
	

		<h3> Reply to comment</h3>
		<%= render "comments/form"%>

	<br/>
	<hr/>
	<br/>

	<%= link_to "Edit", edit_post_path(@post), class: "button"%>
	<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?" }, class: "button"%>